#3 issueの改修
OthloTech/wwOthlo pull request #4
Opened 2018-04-03 15:24 UTC by yuvernacrew

- #3 のバグ改修
- ついでにスタイルの微調整(sp対応少々おまち。。。。)

2018-04-06 14:02 UTC, yuvernacrew commented
⚠︎yoshikawaのとコンフリクトするとおもうのでできたら先にyoshikawaのを通して欲しいです。

2018-04-07 05:34 UTC, haseaki0503 requested changes
hrefが仮置きで#になってるけど、<?php the_permalink() ?>を入れてほしいです。

2018-04-07 07:40 UTC, YoshikawaTaiki commented
コンフリクト発生したので、解決お願いします。はせあきのhref部分以外で改善点あれば、issueやSlackで共有します！

2018-04-07 07:44 UTC, yoshikawa approved these changes
home.phpのイベントのリンクは後で自分で治しますので、よろしくお願いします。

2018-04-13 11:25 UTC, haseaki0503 approved these changes

2018-04-13 14:40 UTC, merged